<header>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">


  <div class="header">
      <div> 
        <?php include './includes/nav.inc'; ?>
      </div> 
      <div> 
        <div class="col-md-6">
    </div> 
  </div>

</div>
    <script src="js/main.js"></script>
</header>