        <nav>
          <select id="dropdown" onchange="navigateToPage()" style="width: 100%; text-align: center;">
            <option value="" disabled selected>Select an Option</option>
            <option value="index.php">Home</option>
            <option value="pets.php">Pets</option>
            <option value="add.php">Add A Pet</option>
            <option value="gallery.php">Gallery</option>
          </select>
        </nav>