<header>
  <div class="header">
    <div class="flex-container flex-start">
      <li class="flex-item" style="text-align: center;">
        <img src="images/logo.png" alt="Pets Victoria Logo" width="50" height="50">
      </li>
      <li class="flex-item" style="text-align: center;">
      <?php include './includes/nav.inc'; ?>
      </li>
      <li class="flex-item" style="text-align: right;">
        <div class="search-bar">
          <input type="search" id="search" placeholder="Search..." style="width: 100%; text-align: right;">
          <span class="material-symbols-outlined">
            search
          </span>
        </div>
      </li>
    </div>
  </div>
    <script src="js/main.js"></script>
</header>