<header> 
    <nav> 
        <select id="dropdown" onchange="navigateToPage()"> 
        <option value="no value is relevant">Select an Option</option>
                   
        <option value="index.html">Home</option>
        <option value="pets.html">Pets</option>
        <option value="add.html">Add A Pet</option>
        <option value="gallery.html">Gallery</option>
    </nav>
</header> 